version: '3.8'

services:
  sacco-banking-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sacco-banking-local
    ports:
      - "8084:8080"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/v1/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - sacco-network

networks:
  sacco-network:
    driver: bridge
