version: '3.8'

services:
  sacco-banking-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sacco-banking-local
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      # Neon Database Configuration (same as Render)
      - NEON_DB_URL=jdbc:postgresql://ep-soft-bar-afkxow8k-pooler.c-2.us-west-2.aws.neon.tech:5432/neondb?sslmode=require
      - NEON_DB_USERNAME=neondb_owner
      - NEON_DB_PASSWORD=npg_2kVFGq3uQSoW
      # JWT Configuration
      - JWT_SECRET=local-test-jwt-secret-key-for-development-only-change-in-production
      - JWT_EXPIRATION=86400000
      # M-Pesa Configuration (using sandbox/mock)
      - MPESA_API_URL=https://sandbox.safaricom.co.ke
      - MPESA_CONSUMER_KEY=your-test-consumer-key
      - MPESA_CONSUMER_SECRET=your-test-consumer-secret
      - MPESA_PASSKEY=your-test-passkey
      - MPESA_SHORTCODE=174379
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/v1/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - sacco-network

networks:
  sacco-network:
    driver: bridge