services:
  - type: web
    name: sacco-banking-api
    runtime: docker
    plan: free
    region: singapore  # Options: singapore, frankfurt, oregon, virginia
    branch: main
    dockerfilePath: ./Dockerfile

    envVars:
      # Database config - Updated for Neon
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: NEON_DB_URL
        value: jdbc:postgresql://ep-soft-bar-afkxow8k-pooler.c-2.us-west-2.aws.neon.tech:5432/neondb?sslmode=require
      - key: NEON_DB_USERNAME
        value: neondb_owner
      - key: NEON_DB_PASSWORD
        sync: false  # set in Render dashboard as: npg_2kVFGq3uQSoW

      # JWT Configuration
      - key: JWT_SECRET
        sync: false  # set a strong secret in Render dashboard
      - key: JWT_EXPIRATION
        value: "86400000"

      # M-Pesa Configuration
      - key: MPESA_API_URL
        value: https://sandbox.safaricom.co.ke  # or your preferred M-Pesa API URL
      - key: MPESA_CONSUMER_KEY
        sync: false  # set in Render dashboard
      - key: MPESA_CONSUMER_SECRET
        sync: false  # set in Render dashboard
      - key: MPESA_PASSKEY
        sync: false  # set in Render dashboard
      - key: MPESA_SHORTCODE
        value: "174379"

      # JVM options for Render's free tier
      - key: JAVA_OPTS
        value: -Xmx400m -Xms200m -XX:+UseG1GC -XX:MaxGCPauseMillis=100

    healthCheckPath: /api/v1/actuator/health

    buildFilter:
      paths:
        - src/**
        - pom.xml
        - mvnw
        - .mvn/**
        - Dockerfile
        - application*.yml
      ignoredPaths:
        - src/test/**
        - "**/*.md"
        - docs/**
        - "**/.git/**"

    autoDeploy: true