server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: sacco-banking-system

  datasource:
    url: ${NEON_DB_URL}
    username: ${NEON_DB_USERNAME}
    password: ${NEON_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: ${JWT_SECRET:default-secret}
  expiration: ${JWT_EXPIRATION:86400000}

mpesa:
  api-url: ${MPESA_API_URL:https://sandbox.safaricom.co.ke}
  consumer-key: ${MPESA_CONSUMER_KEY:default-key}
  consumer-secret: ${MPESA_CONSUMER_SECRET:default-secret}
  passkey: ${MPESA_PASSKEY:default-pass}
  shortcode: ${MPESA_SHORTCODE:174379}

logging:
  level:
    com.sacco.banking: DEBUG
