server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: sacco-banking-system
  datasource:
    url: jdbc:postgresql://ep-soft-bar-afkxow8k-pooler.c-2.us-west-2.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_2kVFGq3uQSoW
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-very-secure-secret-key-here}
  expiration: 86400000 # 24 hours

# M-Pesa Configuration
mpesa:
  api-url: ${MPESA_API_URL:https://sandbox.safaricom.co.ke}
  consumer-key: ${MPESA_CONSUMER_KEY:your-consumer-key}
  consumer-secret: ${MPESA_CONSUMER_SECRET:your-consumer-secret}
  passkey: ${MPESA_PASSKEY:your-passkey}
  shortcode: ${MPESA_SHORTCODE:174379}

# Logging
logging:
  level:
    com.sacco.banking: DEBUG