server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1

spring:
  application:
    name: sacco-banking-system

  datasource:
    url: jdbc:postgresql://db.qpvcxrywpyaithlpwprz.supabase.co:5432/postgres
    username: postgres
    password: Yagnesh!2
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          time_zone: UTC

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 hours

# M-Pesa Configuration
mpesa:
  api-url: ${MPESA_API_URL:https://sandbox.safaricom.co.ke}
  consumer-key: ${MPESA_CONSUMER_KEY:your-consumer-key}
  consumer-secret: ${MPESA_CONSUMER_SECRET:your-consumer-secret}
  passkey: ${MPESA_PASSKEY:your-passkey}
  shortcode: ${MPESA_SHORTCODE:174379}

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

# Production logging
logging:
  level:
    com.sacco.banking: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.springframework.web: WARN
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"